DomainName = "example.com"
RR = "@"
Endpoint = "https://alidns.aliyuncs.com/"
AccessKeyId = "************************"
AccessKeySecret = "******************************"
Interval = 10
GetIpFrom = "taobao.com" # taobao.com / ip.cn
